services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: osipover
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"